### ISSUE TITLE
Infura queried on window claim page where it's not needed

### ISSUE THREAD

**Issue by kolya182** [pooltogether/pooltogether-reference-pool-ui#36]
When on token claim window presented with static results, frontends queries Infura like crazy. Feel free to close it if not relevant.
`URL`: https://app.pooltogether.com/account?address=0x......&claim=1
`Video`: 

https://user-images.githubusercontent.com/3277207/108784042-537df180-7523-11eb-9a6d-859c4942b3ad.mov

**Comment by chuckbergeron** [comment]
Thanks @kolya182 ! Yeah there's a plethora of optimization improvements we could make to the apps. Less calls to Infura is definitely up there! Cheers
