### ISSUE TITLE
Total supply clarification needed

### ISSUE THREAD

**Issue by CruiseMan** [pooltogether/pooltogether-reference-pool-ui#39]
First time user, not sure what does `Total supply mean` ?. Is it what I'm max out to deposit or already deposited. Especially confusing considering zeros above. And would be good to have explanation why it's limited to 10000 ?

<img width="389" alt="Screen Shot 2021-02-26 at 2 24 10 PM" src="https://user-images.githubusercontent.com/15807643/109361811-a20ff080-7881-11eb-877f-4f3ae142e086.png">

**Comment by chuckbergeron** [comment]
Hey @CruiseMan - this is for issues with code relating to the reference app. To discuss the flagship app you can do that on the Discord: https://discord.gg/hxPhPDW - many will be able to help you out there!
